spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my-portfolio?createDatabaseIfNotExist=true
    username: root
    password: Sonu123@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: sjha9563@gmail.com
    password: egyz yjfi omok iywf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
  
    
logging:
  level:
    org.springframework.security: DEBUG


server:
  port: ${SERVER_PORT:8089}